print("Dame el numero x")
x = input()
print("Dame el numero y")
y = input()

suma = int(x) + int(y)
print("La suma de x e y es: ", suma)    
resta = int(x) - int(y)
print("La resta de x e y es: ", resta)  
multiplicacion = int(x) * int(y)
print("La multiplicacion de x e y es: ", multiplicacion)
division = int(x) / int(y)
print("La division de x e y es: ", division)
potencia = int(x) ** int(y)
print("La potencia de x e y es: ", potencia)